# matrix operations in numpy

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Create matrices

In [2]:
## create square matrices
m = np.matrix("1 2 3; 4 5 6; 7 8 9")
# a handy shortcut for np.matrix
print(m)
m = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# standard array way to create things works too
print(m)
a = np.array("1 2 3; 4 5 6; 7 8 9")
# shortcut does not work for np.array
print(a)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 2 3; 4 5 6; 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
# create row matrices
n = np.matrix([3,2,1])
print(n)
b = np.array([[3,2,1]])
print(b)

[[3 2 1]]
[[3 2 1]]


## Transposition

In [4]:
m = np.matrix(np.arange(12).reshape(3,4) + 1)
print(m)
print("transposed\n", m.T)
print("reshaped\n", m.reshape(4,3))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
transposed
 [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
reshaped
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Matrix multiplication

In [5]:
## multiply matrices
print(np.dot(n, m))
print(n.dot(m))
print( n @ m)
# python >= 3.5
## multiply arrays
print(np.dot(b, a))
print(b.dot(a))
print(b @ a)


[[22 28 34 40]]
[[22 28 34 40]]
[[22 28 34 40]]
[[18 24 30]]
[[18 24 30]]
[[18 24 30]]


In [6]:
## powers
m = np.matrix("1 2 3; 4 5 6; 7 8 9")
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m**2)
# m**2 = m @ m
print(a**2)
# a**2 is computed element-wise

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


## Rotation matrix

In [7]:
def rot(alpha):
    a = alpha*np.pi/180
    return np.matrix([[np.cos(a), -np.sin(a)], [np.sin(a), np.cos(a)]])

def plotFigure(A):
    plt.figure(figsize=(8,8))
    # set figure size
    plt.grid(b=True)
    # show grid
    min_limit = np.min(A) - np.max(A)*2.0
    max_limit = np.max(A) + np.max(A)*2.0
    plt.axes().set_xlim((min_limit, max_limit))
    plt.axes().set_ylim((min_limit, max_limit))
    # set limits (not the best ones but good enough)
    plt.axes().set_aspect('equal')
    # ensure units are equal along the axes
    plt.plot(A[:,0], A[:,1])
    # plot x, y
    plt.axhline(0, color='black', linestyle = 'dashed')
    plt.axvline(0, color='black',linestyle = 'dashed')
    # draw the axes

plotFigure(A @ rot(-30))

NameError: name 'A' is not defined

In [ ]:
def rot(alpha):
    a = alpha*np.pi/180
    return np.matrix([[np.cos(a), -np.sin(a)], [np.sin(a), np.cos(a)]])

plotFigure(A @ rot(-30))

In [18]:
p = np.matrix("1, 2; 3, 4; 5, 6")
p

p2 = np.matrix('1,2;-1,2')
p2

p.dot(p2)
p @ p2

matrix([[-1,  6],
        [-1, 14],
        [-1, 22]])