In [2]:
import numpy as np

In [3]:
a = np.random.normal(size=(2,2))
print(a)
## matrix rank
print(np.linalg.matrix_rank(a))
print(np.linalg.det(a))

[[0.94157734 0.60340244]
 [0.18510686 2.3286395 ]]
2
2.0809002539998054


## Inverse matrix

In [4]:
a1 = np.linalg.inv(a)
print(a1)
print("\n", a1 @ a)
print("\n", a @ a1)
print("\n", a @ a1 - np.eye(2))

[[ 1.11905388 -0.28997182]
 [-0.08895518  0.45248557]]

 [[1. 0.]
 [0. 1.]]

 [[1.00000000e+00 0.00000000e+00]
 [2.77555756e-17 1.00000000e+00]]

 [[0.00000000e+00 0.00000000e+00]
 [2.77555756e-17 0.00000000e+00]]


## (Near) singular matrices

In [5]:
## singular matrix
a = np.matrix(np.arange(1,10).reshape(3,3))
print(a)
print("rank=", np.linalg.matrix_rank(a))
np.linalg.inv(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
rank= 2


matrix([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

In [6]:
b = a + 0.001*np.eye(3)
print(b)
print("rank=", np.linalg.matrix_rank(b))
b1 = np.linalg.inv(b)
print("\n", b1@b)
print('\n', b1@b - np.eye(3))

print("condition number\n", np.linalg.cond(b))

[[1.001 2.    3.   ]
 [4.    5.001 6.   ]
 [7.    8.    9.001]]
rank= 3

 [[ 1.00000000e+00 -2.27373675e-13 -3.61551528e-13]
 [ 2.27373675e-13  1.00000000e+00  3.40461273e-13]
 [-8.52651283e-14  0.00000000e+00  1.00000000e+00]]

 [[-4.26325641e-13 -2.27373675e-13 -3.61551528e-13]
 [ 2.27373675e-13  0.00000000e+00  3.40461273e-13]
 [-8.52651283e-14  0.00000000e+00  1.18349774e-13]]
condition number
 16849.05394510901


## Eigenvalues

In [7]:
a = np.matrix(np.arange(1,10).reshape(3,3))
print(a)
ev = np.linalg.eig(a)
print('\neigenvalues\n', ev)
val, vec = np.linalg.eig(a)
print('\neigenvalues\n', val)
print('\neigenvectors\n', vec)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

eigenvalues
 (array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]), matrix([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

eigenvalues
 [ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]

eigenvectors
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


## diagonalization

In [8]:
a = np.matrix(np.arange(1,10).reshape(3,3))
a = 0.5*(a + a.T)
print(a)
val, vec = np.linalg.eig(a)
print('\neigenvalues\n', val)
print('\neigenvectors\n', vec)
L = np.diag(val)
C = vec
print('\n', C)
C1 = np.linalg.inv(C)
print('\nC inverse\n', C1)
print('\ndiagonal form\n', C @ L @ C1)

[[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]

eigenvalues
 [ 1.64582364e+01 -1.45823643e+00  8.30056137e-16]

eigenvectors
 [[-0.35162514 -0.84243284  0.40824829]
 [-0.55335618 -0.1647127  -0.81649658]
 [-0.75508721  0.51300744  0.40824829]]

 [[-0.35162514 -0.84243284  0.40824829]
 [-0.55335618 -0.1647127  -0.81649658]
 [-0.75508721  0.51300744  0.40824829]]

C inverse
 [[-0.35162514 -0.55335618 -0.75508721]
 [-0.84243284 -0.1647127   0.51300744]
 [ 0.40824829 -0.81649658  0.40824829]]

diagonal form
 [[1. 3. 5.]
 [3. 5. 7.]
 [5. 7. 9.]]
