# Linear algebra

This is a lab that helps you learn linear algebra (and the related numpy commands.)  Consult Greene "Econometric Analysis" Appendix A when solving these problems.


Import appropriate packages

In [2]:
import IPython
print("IPython version:      %6.6s (need at least 1.0)" % IPython.__version__)

# Numpy is a library for working with Arrays
import numpy as np
print("Numpy version:        %6.6s (need at least 1.7.1)" % np.__version__)

# Pandas makes working with data tables easier
import pandas as pd
print("Pandas version:       %6.6s (need at least 0.11.0)" % pd.__version__)

IPython version:       6.2.1 (need at least 1.0)
Numpy version:        1.14.0 (need at least 1.7.1)
Pandas version:       0.22.0 (need at least 0.11.0)


## 1 Matrix multiplication
* create the following matrices:
a = [ 1 2 3 4], b = [5 6 7 8 ]'
(note: b includes the transpose sign)
* compute the following matrix products $a \cdot b$ and $a' \cdot b'$

In [12]:
a = np.matrix("1, 2, 3, 4")
b = np.matrix("5, 6, 7, 8")
b = b.T
print(a * b)


ap = a.T
bp = b.T
print(ap * bp)


[[70]]
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


## 2 Linear (in)dependence
Consider three vectors:
a = [1 2 3 4],
b = [5 6 7 8] and
c = [9 10 11 12]

* are these vectors linearly independent?  Calculate the rank, a related determinant, and show how they are related/unrelated

In [24]:
b = np.matrix("5, 6, 7, 8")
c = np.matrix("9, 10, 11, 12")
matrix = np.matrix("1, 2, 3, 4; 5, 6, 7, 8; 9, 10, 11, 12")

print(np.linalg.matrix_rank(matrix))
print(np.linalg.det(matrix * matrix.T))

2
0.0


## 3 Find the inverses of the following matrices:


A = [ <br/>
    1 2 3 4 <br/>
5 6 7 8 <br/>
-1 10 11 12 <br/>
13 14 15 17 ],

B = [ <br/>
    1 0 0 <br/>
     0 4 0 <br/>
     0 0 16]

and

C = [ <br/>
    1 2 3 4 <br/>
      5 6 7 8 <br/>
      9 10 11 12 <br/>
      13 14 15 17 ]

* Check the results by left- and right multiplication of the inverse.  Explain.

In [33]:
A = np.matrix("1, 2, 3, 4; 5, 6, 7, 8; -1, 10, 11, 12; 13, 14, 15, 17 ")

a1 = np.linalg.inv(A)
print(a1)
print("\n", a1 @ A)
print("\n", A @ a1)
# print("\n", A @ a1 - np.eye(2))

B = np.matrix("1, 0, 0; 0, 4, 0; 0, 0, 16")

b1 = np.linalg.inv(B)
print(b1)
print("\n", b1 @ B)
print("\n", B @ b1)
# print("\n", B @ b1 - np.eye(2))

C = np.matrix("1, 2, 3, 4; 5, 6, 7, 8; -1, 10, 11, 12; 13, 14, 15, 17 ")

c1 = np.linalg.inv(C)
print(c1)
print("\n", c1 @ C)
print("\n", C @ c1)
# print("\n", C @ c1 - np.eye(2))


[[-1.00000000e-01  2.00000000e-01 -1.00000000e-01  2.04964251e-16]
 [ 4.50000000e-01 -2.65000000e+00  2.00000000e-01  1.00000000e+00]
 [-2.60000000e+00  5.70000000e+00 -1.00000000e-01 -2.00000000e+00]
 [ 2.00000000e+00 -3.00000000e+00 -7.40148683e-17  1.00000000e+00]]

 [[ 1.00000000e+00 -1.99840144e-15 -2.44249065e-15 -2.88657986e-15]
 [-1.77635684e-15  1.00000000e+00 -1.77635684e-15 -2.66453526e-15]
 [ 1.33226763e-15  8.88178420e-16  1.00000000e+00  1.77635684e-15]
 [ 4.44089210e-16  1.77635684e-15  1.77635684e-15  1.00000000e+00]]

 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  7.10542736e-15  1.00000000e+00 -3.55271368e-15]
 [ 0.00000000e+00 -1.42108547e-14  0.00000000e+00  1.00000000e+00]]
[[1.     0.     0.    ]
 [0.     0.25   0.    ]
 [0.     0.     0.0625]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[-1.00000000e-01  2.00000000e-01 -1.0

## 4 Characteristic roots
* Find the roots (eigenvalues) of the matrices A, B, C above.
* Calculate the condition numbers of these matrices in two ways: the default numpy way, and in this way as it is explained in Greene (2003, page 829)
* Explain the results

In [34]:
evA = np.linalg.eig(A)
print('\neigenvalues A\n', evA)
val, vec = np.linalg.eig(A)
print('\neigenvalues A\n', val)
print('\neigenvectors A\n', vec)

evB = np.linalg.eig(B)
print('\neigenvalues B\n', evB)
val, vec = np.linalg.eig(B)
print('\neigenvalues B\n', val)
print('\neigenvectors B\n', vec)


evC = np.linalg.eig(C)
print('\neigenvalues C\n', evC)
val, vec = np.linalg.eig(C)
print('\neigenvalues C\n', val)
print('\neigenvectors C\n', vec)


eigenvalues A
 (array([35.83449756,  1.34371891, -1.6853005 , -0.49291597]), matrix([[-0.15251646, -0.1275233 ,  0.22153696,  0.08211323],
        [-0.35160514, -0.13224317, -0.177807  , -0.38931136],
        [-0.50813247,  0.81206955,  0.73737404,  0.80513068],
        [-0.77130664, -0.55388862, -0.61285036, -0.43983936]]))

eigenvalues A
 [35.83449756  1.34371891 -1.6853005  -0.49291597]

eigenvectors A
 [[-0.15251646 -0.1275233   0.22153696  0.08211323]
 [-0.35160514 -0.13224317 -0.177807   -0.38931136]
 [-0.50813247  0.81206955  0.73737404  0.80513068]
 [-0.77130664 -0.55388862 -0.61285036 -0.43983936]]

eigenvalues B
 (array([ 1.,  4., 16.]), matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

eigenvalues B
 [ 1.  4. 16.]

eigenvectors B
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

eigenvalues C
 (array([35.83449756,  1.34371891, -1.6853005 , -0.49291597]), matrix([[-0.15251646, -0.1275233 ,  0.22153696,  0.08211323],
        [-0.35160514, -0.13224317, -0.177807  , -0.